from app.models import db, Product, environment, SCHEMA

def seed_products():
    products = (
        [1, 'Crystal Birthstone Necklace for Mom, Personalized Family Tree Necklace, Mom\'s Birthstone Necklace, Grandma Necklace Gift', 'Crystal Birthstone Necklace for Mom, Personalized Family Tree Necklace, Mom\'s Birthstone Necklace, Grandma Necklace Gift', 30.71, 1, 10],
        [2, 'Baby Girl First Christmas outfit, 1st christmas outfit, red gold christmas outfit, Christmas tutu outfit, Christmas dress, red tutu', 'Baby\'s 1st Christmas Outfit in glittering colors! For boy\'s i can make in non glitter red and green. LEGWARMERS ARE OUT OF STOCK!!! Makes great photo props for your new born.', 15.29, 2, 20],
        [3, 'Botanical Print Set of 4 - Botanical Illustration - Botanical Art Print - Art Prints - Vintage Botanical Print Set of 4 - Botanical Poster', 'This is for a set of 4 prints of a Botanical Floral illustration that has been hand painted and were found in an Antique natural history text book. The original has been digitally enhanced and are printed on heavy matte photo paper.', 38.00, 3, 5],
        [4, 'Personalized Wooden Handmade Music Box,Christmas Music Box,Wooden Horse Musical Carousel,Horse Music Box, Musical Carousel,Heirloom Carousel', 'You can engrave your baby\'s name or other content on this music box, but it\'s best not to exceed 9 characters.There are 6 fonts to choose from. You can also choose not to engrave if your preferred font is not available.', 34.31, 4, 2],
        [5, 'Crystal Suncatchers, Light Catcher, Boho Decor, Moon Evil Eye Window Prism, Witchy Decor, Housewarming Gift, Indie Room Decor', 'Brighten your day with this colorful Fairy Crystals Suncatchers! When bright sunlight hits this prism, it transforms the light into beautiful rainbows. Let the sunshine in and color your world!', 11.59, 5, 15],
        [1, 'Gold Name Necklace, Script Name Necklace, Personalized Gift, Handmade Name Necklace, Mother\'s Day Gift, Bridesmaid Gift, Gift For Her', 'This is a Personalized Name necklace. You can also choose it for your friends, family and yourself on some special days', 19.5, 1, 10],
        [2, 'Dainty Raw Crystal Necklace, Genuine Wire Wrapped Crystal, Choose your Crystal, Powerful Healing Crystal Necklaces, High Quality Crystals', 'Beautiful, Genuine, Raw wire-wrapped crystals!Choose your powerful Crystal- Choose your wire color- Choose your necklace type!', 8.45, 1, 50],
        [3, 'Family Necklace • Personalized Gift • Linked Circle Necklace • Custom Children Name Rings • Eternity Necklace • Mother Gift • NM30F30', '• It\'s dainty and can be worn every day • A special piece you\'ll treasure • High quality materials and attention to detail • Personalized: This design can be customized with your Roman Numerals, Messages, Coordinates or Names.', 29.40, 1, 200],
        [4, 'Christmas Sweatshirt, Womens Christmas Sweatshirt, Christmas Sweatshirts for Women, Christmas Women,Merry Christmas Sweatshirt', 'If you want to add or change anything on the existing design that we show in the display picture, please contact with the seller from message box to ask if the changes and additional request can be done or not.', 11.39, 1, 60],
        [5, 'Hand Knitted Boot Cuffs Leg Warmers 2in1 Cream Tweed and Beige Cafe Latte', 'Hand knit leg warmers 2in1, hand made, soft acrylic yarn, color cream tweed and beige (cafe latte), long aprox. 21cm (8,2 in), delivery time - 14-16 days', 26.00, 2, 20],
        [1, 'Genuine Leather Handbags for Women Handmade Purses Top Handle Shoulder Bag Vintage Real Leather Crossbody Personalization Satchel Handbag', 'Material : Genuine leather + polyester. Dimensions : 20x11x17cm / 7.87x4.33x6.69 inches(L*W*H). Structure : 1 zipper compartment (1 open pocket and 2 zipper pockets inside).', 127.00, 2, 20],
        [2, 'Light Ivory Flower Girl Dress, Long Sleeve Flower Girl Dress, Lace Flower Girl Dress, Navy Flower Girl Dress, Tulle Flower Girl Dress', 'Please see the size chart in last picture of listing to choose a correct size before ordering, this is VERY IMPORTANT.', 69.30, 2, 20],
        [3, 'Ceramic Thinking Vase, Ceramic Flower Vase Decorative Bud Vase, Floral Vase, Plants Flower Container Flower Planter Pot', 'SIZE: The height of the large minimalist vase is 7.5 inches and the width is 5.5 inches. This can also alone as desk or table decor. Material: Our modern art vases is made of ceramic fired with high-temperature technology.', 48.74, 3, 20],
        [4, 'Funny Kitchen Towels - Kitchen Decor - Hostess Gift - Dish Towels - Housewarming Gift - Gift For Mom - Wedding Shower Gift - Hand Towel', 'It\'s a scientific fact that puns are the greatest form of humor. Now with these wonderful towels, you can keep them hanging in your kitchen! Made of microfiber to be super absorbent, these towels are made to be useful as well as funny.', 11.95, 3, 200],
        [5, 'UnBoxMe Warm + Cozy Care Package For Her, Thinking Of You, Holiday Gift For Women, Birthday Gift, Christmas Care Package, Secret Santa Gift', 'Send a hug in a box with this warm + cozy themed care package. This makes the perfect birthday gift, pick me up gift, or just to show someone you are thinking of them! Each box is hand-packed with love in Denver, CO.', 40.80, 3, 50],
        [1, 'Winter Candle//Christmas Candle//Soy Candle//Choose Your Scent//16 oz Candle/Half Pint Mason Jar Candle//Gift Candle//Sweater Candle', 'Each candle is dye free the 16 oz burns up to 100+ hrs. and the 8 oz burns up to 50+ hours, and being 100% soy wax with a 100% cotton wick, you can get maximum enjoyment out of this scent without polluting your home or air.', 15.00, 3, 60],
        [2, 'Guitar Pick Case; Banjo Mandolin Dobro Uke Pick & Slide Holder Box; Unique Christmas Gift for Musicians; Birthday Holiday Anytime Music Gift', 'Perfect for gift giving they are a unique keepsake trinket box for any musician. Ideal for celebrating 5th (traditional), 6th (modern) or 7th (desktop) anniversaries.', 35.00, 4, 30],
        [3, 'To-do List,Sliding Routine Chart with a set of stickers, Kids Daily Tasks,Housekeeping Schedule | Magnetic | Dry-erase | multiple colors', 'The slider will be a little tight the first time you use it, the first time you get the rountine chart please slide the slider repeatedly several times can make the slider loose.', 18.74, 4, 70],
        [4, 'Name Puzzle for Toddler Woodland Animals Toys, Baby Boy 1st Birthday Gift, Kids Name Puzzle 2nd, 3rd Birthday Gift, Nursery Montessori Toy', 'Our puzzle with forest animals is a fun learning tool that encourages fine motor skills, name recognition, and spelling. Made of non-toxic birch plywood, our name board contains child-friendly elements (letters) that are easy to get out and play with.', 21.34, 4, 200],
        [5, 'Teepee Tent for Kids, Teepee, Kids Teepee, Teepee Tent, Play Tent, Tee Pee, Tent for kids, Kids Tent, Tee Pee Tent, Kids Teepee Tent, Tipi', 'Teepee set includes everything you may need to create the perfect place for your baby or decoration for any occasion.', 89.10, 4, 60],
        [1, 'Stained glass Christmas cardinal gift, window hangings suncatcher, flower suncatcher, bird stained glass', 'Stained glass ornament is made individually. This is an example. We make a new one to your order. The hue of stained glass may vary.', 58.70, 5, 20],
        [2, 'GICLEE PRINT Large Art Abstract Painting Blue White Wall Art Home Decor PAPER Prints Coastal Wall Decor Marbled Seascape Beach - Christine', '"Drifting Away" Giclee Print / Paper Print of Original Art Blue Abstract Painting Marbled effect in shades of aqua, blue, sea foam green, white, grey, light blue, navy blue with gold accents. Large art, wall art, coastal home decor.', 35.10, 5, 20],
        [3, 'Felted Cria Huacaya Alpaca Miniature Decoration: Handmade Sculpture Ornament', 'FREE chullo hat! These fabulous needle felted alpacas are made entirely by hand, so each piece is unique. They stand 5.5 inches tall, and each little face is sewn and created with love.', 24.00, 5, 20],
        [4, 'Original Acrylic Painting On Canvas Texture Wall Art Knife Abstract Art Wall art for living room,bedroom,office,Personalized Christmas gifts', 'Size: It can be selected and customized. Product Status: No frame, unstretched, not ready to hang, only canvas sent IN ROLL with 2 inches border for framing.', 99.20, 5, 20],
        [5, 'Kintsugi Bowl, Kintsugi Blue Celestial Bowl, Kintsugi Pottery, Gift for Her, Home Decor, Minimalist, Holiday Decor, Kintsugi Blue Bowl', 'This stunning Kintsugi bowl, is handmade and beautiful blue celestial glaze. It has an amazing dark star color and a unique Kintsugi gold repair style.', 52.00, 5, 20]
    )
    for i in products:
        product = Product(seller_id=i[0], name=i[1], description=i[2], price=i[3], category_id=i[4], avalibility=i[5])
        db.session.add(product)
        db.session.commit()

def undo_products():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.products RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM products")

    db.session.commit()
